[package]
name = "waclient"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive", "env"] }
dirs = "5"
tabwriter = "1.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
wispers-access-sdk = { path = "../sdk" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
